### ISSUE TITLE
git repository url should be modified

### ISSUE THREAD

**Issue by sakaia** [NVIDIA/5t5g#1]
At github,  following description on README.md should be modified from

```
git clone --recurse-submodules ssh://git@gitlab-master.nvidia.com:12051/eagostini/5t5g.git
```

to 

```
git clone --recurse-submodules http://github.com/NVIDIA/5t5g
```

on
https://github.com/NVIDIA/5t5g/blob/master/README.md

**Comment by e-ago** [comment]
Nice catch, thanks!
I've updated the README
